###
GET http://localhost:13000/db
###

POST http://localhost:13000/db
Content-Type: application/json

{
    "filters": {"test": "test"},
    "type": "chart"
}

###
GET http://localhost:13000/api/indicators
###

DELETE http://localhost:13000/db/19b28545-d1a8-4e9e-a53d-12d1b7a98f40
Content-Type: application/json

###
POST http://localhost:13000/mcp/process
Content-Type: application/json

{
    "message": "Search FRED series for 'unemployment rate for retail.  Use the series id to add a widget with title 'Retail Unemployment Rate'"
}